In [7]:
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot as plt

pd.options.display.max_rows=10
pd.options.display.float_format="{:.1f}".format

In [8]:
training_df=pd.read_csv(filepath_or_buffer="https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv")

training_df["median_house_value"] /= 1000.0

training_df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.3,34.2,15.0,5612.0,1283.0,1015.0,472.0,1.5,66.9
1,-114.5,34.4,19.0,7650.0,1901.0,1129.0,463.0,1.8,80.1
2,-114.6,33.7,17.0,720.0,174.0,333.0,117.0,1.7,85.7
3,-114.6,33.6,14.0,1501.0,337.0,515.0,226.0,3.2,73.4
4,-114.6,33.6,20.0,1454.0,326.0,624.0,262.0,1.9,65.5

In [9]:
training_df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.0,17000.0,17000.0,17000.0,17000.0,17000.0,17000.0,17000.0,17000.0
mean,-119.6,35.6,28.6,2643.7,539.4,1429.6,501.2,3.9,207.3
std,2.0,2.1,12.6,2179.9,421.5,1147.9,384.5,1.9,116.0
min,-124.3,32.5,1.0,2.0,1.0,3.0,1.0,0.5,15.0
25%,-121.8,33.9,18.0,1462.0,297.0,790.0,282.0,2.6,119.4
50%,-118.5,34.2,29.0,2127.0,434.0,1167.0,409.0,3.5,180.4
75%,-118.0,37.7,37.0,3151.2,648.2,1721.0,605.2,4.8,265.0
max,-114.3,42.0,52.0,37937.0,6445.0,35682.0,6082.0,15.0,500.0

In [10]:
def build_model(my_learning_rate):
    model=tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(units=1 ,input_shape=(1,)))
    model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=my_learning_rate),
                  loss='mean_squared_error',
                  metrics=[tf.keras.metrics.RootMeanSquaredError()])
    return model

def train_model(model,df,feature,label,epochs,batch_size):
    history=model.fit(x=df[feature],
                      y=df[label],
                      batch_size=batch_size,
                      epochs=epochs)
    trained_weight=model.get_weights()[0][0]
    trained_bias=model.get_weights()[1]
    epochs=history.epoch
    hist=pd.DataFrame(history.history)
    rmse=hist['root_mean_squared_error']
    return trained_weight,trained_bias,epochs,rmse,history.history
print("Defined build_model and train_model")

Defined build_model and train_model

In [11]:
def plot_the_model(trained_weight,trained_bias,feature,label):
    plt.xlabel(feature)
    plt.ylabel(label)
    
    random_examples=training_df.sample(n=200)
    plt.scatter(random_examples[feature],random_examples[label])

    x0=0
    y0=trained_bias
    x1=random_examples[feature].max()
    y1=trained_bias+(trained_weight*x1)
    plt.plot([x0,x1],[y0,y1],c='r')

    plt.show()

def plot_the_loss_curve(epochs,rmse):
    plt.figure()
    plt.xlabel('Epoch')
    plt.ylabel('Root Mean Squared Error')

    plt.plot(epochs,rmse,label='loss')
    plt.legend()
    plt.ylim([rmse.min()*0.97,rmse.max()])
    plt.show()

In [12]:
learning_rate=0.01
epochs=30
batch_size=30

my_feature="total_rooms"
my_label="median_house_value"

my_model=None

my_model=build_model(learning_rate)
weight,bias,epochs,rmse=train_model(my_model,training_df,my_feature,my_label,epochs,batch_size)

print("\n The learned weight %.4f"% weight)
print("\n The learned bisa %.4f"%bias)

plot_the_model(weight,bias,my_feature,my_label)
plot_the_loss_curve(epochs,rmse)

Epoch 1/30

C:\Users\Sumit Kumar.DESKTOP-FNL8J4G\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

567/567 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 89534.3594 - root_mean_squared_error: 274.4395
Epoch 2/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 932us/step - loss: 28680.7285 - root_mean_squared_error: 169.3277
Epoch 3/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 998us/step - loss: 27203.0254 - root_mean_squared_error: 164.9214
Epoch 4/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - loss: 26095.2168 - root_mean_squared_error: 161.5260
Epoch 5/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 25209.5762 - root_mean_squared_error: 158.7115
Epoch 6/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - loss: 25187.6094 - root_mean_squared_error: 158.6876
Epoch 7/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - loss: 24626.9219 - root_mean_squared_error: 156.8734
Epoch 8/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - loss: 24466.7031 - root_mean_squared_error: 156.3804
Epoch 9/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - loss: 22943.8691 - root_mean_squared_error: 151.4383
Epoch 10/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - loss: 22775.1602 - root_mean_squared_error: 150.9027
Epoch 11/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 21983.9648 - root_mean_squared_error: 148.2633
Epoch 12/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 20914.6582 - root_mean_squared_error: 144.5892
Epoch 13/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - loss: 21502.4941 - root_mean_squared_error: 146.5936
Epoch 14/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - loss: 20625.6836 - root_mean_squared_error: 143.5988
Epoch 15/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - loss: 20740.2852 - root_mean_squared_error: 143.8520
Epoch 16/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - loss: 19870.1445 - root_mean_squared_error: 140.8913
Epoch 17/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - loss: 19199.6055 - root_mean_squared_error: 138.5498
Epoch 18/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - loss: 18284.7852 - root_mean_squared_error: 135.1602
Epoch 19/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - loss: 18213.9512 - root_mean_squared_error: 134.9376
Epoch 20/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - loss: 17757.8223 - root_mean_squared_error: 133.2352
Epoch 21/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 840us/step - loss: 17769.3027 - root_mean_squared_error: 133.2859
Epoch 22/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 17113.8594 - root_mean_squared_error: 130.8121
Epoch 23/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 855us/step - loss: 17524.5137 - root_mean_squared_error: 132.3520
Epoch 24/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 756us/step - loss: 16880.7168 - root_mean_squared_error: 129.9127
Epoch 25/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 837us/step - loss: 16605.5117 - root_mean_squared_error: 128.8503
Epoch 26/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 15860.6689 - root_mean_squared_error: 125.9328
Epoch 27/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 748us/step - loss: 15517.9717 - root_mean_squared_error: 124.5581
Epoch 28/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 15948.9316 - root_mean_squared_error: 126.2202
Epoch 29/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 15617.3408 - root_mean_squared_error: 124.9656
Epoch 30/30
567/567 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - loss: 15392.8584 - root_mean_squared_error: 124.0421

ValueError: too many values to unpack (expected 4)